name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy-to-github-web:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 8.0.x

    # Restore dependencies    
    - name: Restore
      run: dotnet restore ./World.Data.sln
      
    # Build the solution 
    - name: Build
      run: dotnet build ./World.Data.sln

    # Publish the web app into the folder "web-release"
    - name: Publish the Web App
      run: dotnet publish ./World.Data.Web/World.Data.Web.csproj -c Release -o ./web-release --nologo

    # changes the base-tag in index.html from '/' to 'us-presidential-election' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to us-presidential-election
      run: sed -i 's/<base href="\/" \/>/<base href="\/us-presidential-election\/" \/>/g' ./web-release/wwwroot/index.html

    # Commit to gh-pages in order to host the web app
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-github-pages@v3.1.12
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: web-release/wwwroot
    
